const cars = [
  {
    id: "1",
    name: "Lamborghini Huracán",
    price: "AED899/day",
    deposit: true,
    transmission: "Automatic",
    seats: 2,
    luggage: 1,
    category: "Sport",
    images: ["/images/lamborghini.jpg"],
    description:
      "Experience the raw power and iconic design of the Lamborghini Huracán — a perfect blend of performance and Italian craftsmanship.",
  },
  {
    id: "2",
    name: "Rolls Royce Phantom",
    price: "AED1299/day",
    deposit: true,
    transmission: "Automatic",
    seats: 5,
    luggage: 3,
    category: "Luxury",
    images: ["/images/rollsroyce.jpg"],
    description:
      "Step into prestige and grace with the Rolls Royce Phantom — the pinnacle of luxury, comfort, and sophistication.",
  },
  {
    id: "ferrari",
    name: "Ferrari 458",
    price: "AED800/day",
    deposit: true,
    transmission: "Automatic",
    seats: 5,
    luggage: 3,
    category: "Sport",
    images: ["/images/ferrari.jpg"],
    description:
      "Unleash the racer within with the Ferrari 458. Renowned for its thrilling performance, sleek lines, and unmatched agility.",
  },
  {
    id: "mustang",
    name: "Ford Mustang 2024",
    price: "AED450/day",
    deposit: true,
    transmission: "Automatic",
    seats: 4,
    luggage: 3,
    category: "Muscle",
    images: [
      "/images/mustang/mustang.jpeg",
      "/images/mustang/mustang2.jpeg",
    ],
    description:
      "The 2024 Mustang Ecoboost blends American muscle heritage with modern technology for an exhilarating drive across the UAE.",
  },
  {
    id: "dodge-challenger",
    name: "Dodge Challenger 2023",
    price: "AED450/day",
    deposit: true,
    transmission: "Automatic",
    seats: 4,
    luggage: 3,
    category: "Muscle",
    images: [
      "/images/dodge-challenger/1.jpeg",
      "/images/dodge-challenger/2.jpeg",
      "/images/dodge-challenger/3.jpeg",
      "/images/dodge-challenger/4.jpeg",
      "/images/dodge-challenger/5.jpeg",
      "/images/dodge-challenger/6.jpeg",
      "/images/dodge-challenger/7.jpeg",
    ],
    description:
      "Feel the retro spirit reimagined with the 2023 Dodge Challenger — bold design meets turbocharged V4 performance.",
  },
  {
    id: "patrol-2023",
    name: "Patrol 2023",
    price: "AED400/day",
    deposit: true,
    transmission: "Automatic",
    seats: 4,
    luggage: 3,
    category: "SUV",
    images: [
      "/images/nismo/1.jpg",
      "/images/nismo/2.jpg",
      "/images/nismo/3.jpg",
      "/images/nismo/4.jpg",
      "/images/nismo/5.jpg",
    ],
    description:
      "Rule the road with the 2023 Patrol — a perfect SUV for exploring city streets or desert dunes in style and comfort.",
  },
  {
    id: "corvette",
    name: "Chevrolet Corvette 2024",
    price: "AED1200/day",
    deposit: true,
    transmission: "Automatic",
    seats: 2,
    luggage: 3,
    category: "Muscle",
    images: [
      "/images/corvette/1.jpeg",
      "/images/corvette/2.jpeg",
      "/images/corvette/3.jpeg",
      "/images/corvette/4.jpeg",
      "/images/corvette/5.jpeg",
      "/images/corvette/6.jpeg",
      "/images/corvette/7.jpeg",
      "/images/corvette/8.jpeg",
      "/images/corvette/9.jpeg",
      "/images/corvette/10.jpeg",
    ],
    description:
      "Rule the road with the 2023 Patrol — a perfect SUV for exploring city streets or desert dunes in style and comfort.",
  },
  {
    id: "patrol-2023-hawk",
    name: "Nissan patrol 2023 Platinum Black Hawk kit",
    price: "AED450/day",
    deposit: true,
    transmission: "Automatic",
    seats: 2,
    luggage: 3,
    category: "suv",
    images: [
      "/images/nissan-patrol/1.jpg",
      "/images/nissan-patrol/2.jpg",
      "/images/nissan-patrol/3.jpg",
      "/images/nissan-patrol/4.jpg",
    ],
    description:
      "Rule the road with the 2023 Patrol — a perfect SUV for exploring city streets or desert dunes in style and comfort.",
  },

  {
    id: "mustang-2024",
    name: "Ford Mustang 2024",
    price: "AED400/day",
    deposit: true,
    transmission: "Automatic",
    seats: 4,
    luggage: 3,
    category: "Muscle",
    images: [
      "/images/mustang2024/1.jpeg",
      "/images/mustang2024/2.jpeg",
      "/images/mustang2024/3.jpeg",
      "/images/mustang2024/4.jpeg",
    ],
    description:
      "The 2024 Mustang Ecoboost blends American muscle heritage with modern technology for an exhilarating drive across the UAE.",
  },
  {
    id: "nissan-altima",
    name: "Nissan Altima 2023",
    price: "AED250/day",
    deposit: true,
    transmission: "Automatic",
    seats: 4,
    luggage: 3,
    category: "Economy",
    images: [
      "/images/nissan-altima/1.jpeg",
      "/images/nissan-altima/2.jpeg",
      "/images/nissan-altima/3.jpeg",
      "/images/nissan-altima/4.jpeg",
      "/images/nissan-altima/5.jpeg",
      "/images/nissan-altima/6.jpeg",
      "/images/nissan-altima/7.jpeg",
      "/images/nissan-altima/8.jpeg",
    ],
    description:
      "The 2024 Mustang Ecoboost blends American muscle heritage with modern technology for an exhilarating drive across the UAE.",
  },
  {
    id: "bmw-m4-2023",
    name: "BMW M4 2023",
    price: "AED700/day",
    deposit: true,
    transmission: "Automatic",
    seats: 4,
    luggage: 2,
    category: "Sport",
    images: [
      "/images/bmw-m4/1.jpeg",
      "/images/bmw-m4/2.jpeg",
      "/images/bmw-m4/3.jpeg",
    ],
    description:
      "The 2023 BMW M4 combines precision German engineering with raw turbocharged performance — made for those who crave the ultimate driving thrill.",
  },
  {
    id: "g63-2023",
    name: "Mercedes G63 AMG 2023",
    price: "AED1200/day",
    deposit: true,
    transmission: "Automatic",
    seats: 5,
    luggage: 4,
    category: "Luxury",
    images: [
      "/images/g63/1.jpeg",
      "/images/g63/2.jpeg",
      "/images/g63/3.jpeg",
    ],
    description:
      "Make a bold statement with the 2023 G63 AMG — the perfect fusion of luxury, power, and off-road dominance.",
  },
  {
    id: "audi-r8",
    name: "Audi R8 V10",
    price: "AED950/day",
    deposit: true,
    transmission: "Automatic",
    seats: 2,
    luggage: 2,
    category: "Sport",
    images: [
      "/images/audi-r8/1.jpeg",
      "/images/audi-r8/2.jpeg",
      "/images/audi-r8/3.jpeg",
    ],
    description:
      "Redefine your drive with the Audi R8 V10 — iconic design and a screaming engine that delivers pure excitement.",
  },
  {
    id: "camaro-ss",
    name: "Chevrolet Camaro SS 2023",
    price: "AED450/day",
    deposit: true,
    transmission: "Automatic",
    seats: 4,
    luggage: 3,
    category: "Muscle",
    images: [
      "/images/camaro/1.jpeg",
      "/images/camaro/2.jpeg",
      "/images/camaro/3.jpeg",
    ],
    description:
      "With aggressive styling and track-ready performance, the Camaro SS brings muscle car culture into the modern age.",
  },
  {
    id: "tesla-model-s",
    name: "Tesla Model S",
    price: "AED600/day",
    deposit: true,
    transmission: "Automatic",
    seats: 5,
    luggage: 4,
    category: "Electric",
    images: [
      "/images/tesla-model-s/1.jpeg",
      "/images/tesla-model-s/2.jpeg",
    ],
    description:
      "Go electric with the Tesla Model S — unmatched acceleration, cutting-edge tech, and a futuristic driving experience.",
  },
  {
    id: "land-cruiser-2023",
    name: "Toyota Land Cruiser 2023",
    price: "AED500/day",
    deposit: true,
    transmission: "Automatic",
    seats: 7,
    luggage: 5,
    category: "SUV",
    images: [
      "/images/land-cruiser/1.jpeg",
      "/images/land-cruiser/2.jpeg",
    ],
    description:
      "Conquer any terrain with the 2023 Land Cruiser — trusted durability and luxury for the whole family or crew.",
  },
  {
    id: "bentley-bentayga",
    name: "Bentley Bentayga",
    price: "AED1500/day",
    deposit: true,
    transmission: "Automatic",
    seats: 5,
    luggage: 4,
    category: "Luxury",
    images: [
      "/images/bentayga/1.jpeg",
      "/images/bentayga/2.jpeg",
    ],
    description:
      "Ride in opulence with the Bentley Bentayga — a luxury SUV that combines handcrafted excellence with commanding power.",
  },
  {
    id: "kia-k5-2023",
    name: "Kia K5 2023",
    price: "AED200/day",
    deposit: true,
    transmission: "Automatic",
    seats: 5,
    luggage: 3,
    category: "Economy",
    images: [
      "/images/kia-k5/1.jpeg",
      "/images/kia-k5/2.jpeg",
    ],
    description:
      "Sleek and efficient, the 2023 Kia K5 delivers modern features and comfort in an affordable, stylish package.",
  },
  {
    id: "porsche-911",
    name: "Porsche 911 Carrera",
    price: "AED1100/day",
    deposit: true,
    transmission: "Automatic",
    seats: 2,
    luggage: 2,
    category: "Sport",
    images: [
      "/images/porsche-911/1.jpeg",
      "/images/porsche-911/2.jpeg",
    ],
    description:
      "Timeless and thrilling, the Porsche 911 Carrera is the gold standard of precision and prestige in the sports car world.",
  },
  {
    id: "range-rover-vogue",
    name: "Range Rover Vogue 2023",
    price: "AED1000/day",
    deposit: true,
    transmission: "Automatic",
    seats: 5,
    luggage: 4,
    category: "SUV",
    images: [
      "/images/range-rover-vogue/1.jpeg",
      "/images/range-rover-vogue/2.jpeg",
    ],
    description:
      "Make every journey first-class with the Range Rover Vogue — the pinnacle of luxury and all-terrain capability.",
  },
  {
    id: "lexus-lx600",
    name: "Lexus LX 600",
    price: "AED900/day",
    deposit: true,
    transmission: "Automatic",
    seats: 7,
    luggage: 5,
    category: "Luxury",
    images: [
      "/images/lexus-lx600/1.jpeg",
      "/images/lexus-lx600/2.jpeg",
    ],
    description:
      "Elevate your driving experience with the Lexus LX 600 — luxury, power, and unmatched off-road confidence.",
  },
  {
    id: "mercedes-s500",
    name: "Mercedes-Benz S500",
    price: "AED1100/day",
    deposit: true,
    transmission: "Automatic",
    seats: 5,
    luggage: 3,
    category: "Luxury",
    images: [
      "/images/mercedes-s500/1.jpeg",
      "/images/mercedes-s500/2.jpeg",
    ],
    description:
      "Experience elite comfort and technology with the S500 — Mercedes-Benz’s ultimate flagship sedan.",
  },
  {
    id: "bmw-x7",
    name: "BMW X7 2023",
    price: "AED950/day",
    deposit: true,
    transmission: "Automatic",
    seats: 7,
    luggage: 5,
    category: "SUV",
    images: [
      "/images/bmw-x7/1.jpeg",
      "/images/bmw-x7/2.jpeg",
    ],
    description:
      "Big, bold, and luxurious — the BMW X7 is designed to move families in unmatched style and comfort.",
  },
  {
    id: "cadillac-escalade",
    name: "Cadillac Escalade 2023",
    price: "AED1100/day",
    deposit: true,
    transmission: "Automatic",
    seats: 7,
    luggage: 6,
    category: "SUV",
    images: [
      "/images/escalade/1.jpeg",
      "/images/escalade/2.jpeg",
    ],
    description:
      "Command the road with the 2023 Cadillac Escalade — where full-size meets full-luxury.",
  },
  {
    id: "audi-q8",
    name: "Audi Q8 2023",
    price: "AED850/day",
    deposit: true,
    transmission: "Automatic",
    seats: 5,
    luggage: 4,
    category: "SUV",
    images: [
      "/images/audi-q8/1.jpeg",
      "/images/audi-q8/2.jpeg",
    ],
    description:
      "Modern design, advanced tech, and power — the Audi Q8 redefines what a luxury SUV should be.",
  },
  {
    id: "hyundai-elantra",
    name: "Hyundai Elantra 2023",
    price: "AED180/day",
    deposit: true,
    transmission: "Automatic",
    seats: 5,
    luggage: 3,
    category: "Economy",
    images: [
      "/images/elantra/1.jpeg",
      "/images/elantra/2.jpeg",
    ],
    description:
      "Affordable, fuel-efficient, and modern — the Elantra is perfect for exploring the city in comfort.",
  },
  {
    id: "kia-sportage",
    name: "Kia Sportage 2023",
    price: "AED200/day",
    deposit: true,
    transmission: "Automatic",
    seats: 5,
    luggage: 4,
    category: "Economy",
    images: [
      "/images/kia-sportage/1.jpeg",
      "/images/kia-sportage/2.jpeg",
    ],
    description:
      "Compact yet spacious, the Kia Sportage offers the versatility and reliability you need every day.",
  },
  {
    id: "jeep-wrangler",
    name: "Jeep Wrangler Rubicon",
    price: "AED500/day",
    deposit: true,
    transmission: "Automatic",
    seats: 4,
    luggage: 2,
    category: "SUV",
    images: [
      "/images/jeep-wrangler/1.jpeg",
      "/images/jeep-wrangler/2.jpeg",
    ],
    description:
      "Go beyond the pavement with the Jeep Wrangler Rubicon — a true icon of rugged off-road freedom.",
  },
  {
    id: "mini-cooper",
    name: "Mini Cooper Convertible",
    price: "AED350/day",
    deposit: true,
    transmission: "Automatic",
    seats: 4,
    luggage: 2,
    category: "Sport",
    images: [
      "/images/mini-cooper/1.jpeg",
      "/images/mini-cooper/2.jpeg",
    ],
    description:
      "Fun, stylish, and nimble — the Mini Cooper Convertible is perfect for sunny cruises around town.",
  },
  {
    id: "toyota-prado",
    name: "Toyota Prado 2023",
    price: "AED450/day",
    deposit: true,
    transmission: "Automatic",
    seats: 7,
    luggage: 4,
    category: "SUV",
    images: [
      "/images/prado/1.jpeg",
      "/images/prado/2.jpeg",
    ],
    description:
      "A trusted name in off-road capability, the Toyota Prado offers luxury and ruggedness in one SUV.",
  },
  {
    id: "infiniti-qx80",
    name: "Infiniti QX80 2023",
    price: "AED700/day",
    deposit: true,
    transmission: "Automatic",
    seats: 7,
    luggage: 5,
    category: "Luxury",
    images: [
      "/images/infiniti-qx80/1.jpeg",
      "/images/infiniti-qx80/2.jpeg",
    ],
    description:
      "Commanding presence and interior luxury — the Infiniti QX80 is built for the elite family traveler.",
  },
  {
    id: "range-rover-sport",
    name: "Range Rover Sport 2023",
    price: "AED1100/day",
    deposit: true,
    transmission: "Automatic",
    seats: 5,
    luggage: 4,
    category: "Luxury",
    images: [
      "/images/range-sport/1.jpeg",
      "/images/range-sport/2.jpeg",
    ],
    description:
      "Where power meets refinement — the 2023 Range Rover Sport delivers dynamic luxury on every journey.",
  },
  {
    id: "toyota-yaris",
    name: "Toyota Yaris 2023",
    price: "AED150/day",
    deposit: true,
    transmission: "Automatic",
    seats: 4,
    luggage: 2,
    category: "Economy",
    images: [
      "/images/yaris/1.jpeg",
      "/images/yaris/2.jpeg",
    ],
    description:
      "Economical and compact — the Yaris is ideal for navigating urban traffic efficiently and affordably.",
  },
  {
    id: "audi-a6",
    name: "Audi A6 2023",
    price: "AED600/day",
    deposit: true,
    transmission: "Automatic",
    seats: 5,
    luggage: 4,
    category: "Luxury",
    images: [
      "/images/audi-a6/1.jpeg",
      "/images/audi-a6/2.jpeg",
    ],
    description:
      "Smooth, stylish, and packed with technology — the Audi A6 is perfect for business and leisure alike.",
  },
  {
    id: "chevy-tahoe",
    name: "Chevrolet Tahoe 2023",
    price: "AED800/day",
    deposit: true,
    transmission: "Automatic",
    seats: 7,
    luggage: 6,
    category: "SUV",
    images: [
      "/images/tahoe/1.jpeg",
      "/images/tahoe/2.jpeg",
    ],
    description:
      "Spacious and powerful — the Chevy Tahoe is ideal for large families and group trips.",
  },
  {
    id: "honda-civic",
    name: "Honda Civic 2023",
    price: "AED200/day",
    deposit: true,
    transmission: "Automatic",
    seats: 5,
    luggage: 3,
    category: "Economy",
    images: [
      "/images/honda-civic/1.jpeg",
      "/images/honda-civic/2.jpeg",
    ],
    description:
      "Stylish, fuel-efficient, and tech-savvy — the Civic is a favorite among city drivers.",
  },
  {
    id: "mercedes-e300",
    name: "Mercedes-Benz E300",
    price: "AED650/day",
    deposit: true,
    transmission: "Automatic",
    seats: 5,
    luggage: 3,
    category: "Luxury",
    images: [
      "/images/e300/1.jpeg",
      "/images/e300/2.jpeg",
    ],
    description:
      "Blending elegance and performance, the Mercedes E300 is perfect for executive travel.",
  },
  {
    id: "mazda-cx5",
    name: "Mazda CX-5 2023",
    price: "AED250/day",
    deposit: true,
    transmission: "Automatic",
    seats: 5,
    luggage: 4,
    category: "Economy",
    images: [
      "/images/cx5/1.jpeg",
      "/images/cx5/2.jpeg",
    ],
    description:
      "Smart, safe, and stylish — the Mazda CX-5 offers premium features in a budget-friendly crossover.",
  },
  {
    id: "nissan-sentra",
    name: "Nissan Sentra 2023",
    price: "AED180/day",
    deposit: true,
    transmission: "Automatic",
    seats: 5,
    luggage: 3,
    category: "Economy",
    images: [
      "/images/sentra/1.jpeg",
      "/images/sentra/2.jpeg",
    ],
    description:
      "Simple and reliable — the Sentra is a great everyday rental for economy-focused drivers.",
  },
  {
    id: "ford-bronco",
    name: "Ford Bronco 2023",
    price: "AED600/day",
    deposit: true,
    transmission: "Automatic",
    seats: 5,
    luggage: 3,
    category: "SUV",
    images: [
      "/images/bronco/1.jpeg",
      "/images/bronco/2.jpeg",
    ],
    description:
      "Adventure-ready with retro appeal — the Ford Bronco returns with rugged looks and real off-road power.",
  },
];

export default cars;
