const cars = [
  {
    id: "1",
    name: "Lamborghini Huracán",
    price: "$899/day",
    deposit: true,
    transmission: "Automatic",
    seats: 2,
    luggage: 1,
    category: "Sport",
    images: ["/images/lamborghini.jpg"],
    description:
      "Experience the raw power and iconic design of the Lamborghini Huracán — a perfect blend of performance and Italian craftsmanship.",
  },
  {
    id: "2",
    name: "Rolls Royce Phantom",
    price: "$1299/day",
    deposit: true,
    transmission: "Automatic",
    seats: 5,
    luggage: 3,
    category: "Luxury",
    images: ["/images/rollsroyce.jpg"],
    description:
      "Step into prestige and grace with the Rolls Royce Phantom — the pinnacle of luxury, comfort, and sophistication.",
  },
  {
    id: "ferrari",
    name: "Ferrari 458",
    price: "$800/day",
    deposit: true,
    transmission: "Automatic",
    seats: 5,
    luggage: 3,
    category: "Sport",
    images: ["/images/ferrari.jpg"],
    description:
      "Unleash the racer within with the Ferrari 458. Renowned for its thrilling performance, sleek lines, and unmatched agility.",
  },
  {
    id: "mustang",
    name: "Ford Mustang 2024",
    price: "AED450/day",
    deposit: true,
    transmission: "Automatic",
    seats: 4,
    luggage: 3,
    category: "Muscle",
    images: [
      "/images/mustang/mustang.jpeg",
      "/images/mustang/mustang2.jpeg",
    ],
    description:
      "The 2024 Mustang Ecoboost blends American muscle heritage with modern technology for an exhilarating drive across the UAE.",
  },
  {
    id: "dodge-challenger",
    name: "Dodge Challenger 2023",
    price: "AED450/day",
    deposit: true,
    transmission: "Automatic",
    seats: 4,
    luggage: 3,
    category: "Muscle",
    images: [
      "/images/dodge-challenger/1.jpeg",
      "/images/dodge-challenger/2.jpeg",
      "/images/dodge-challenger/3.jpeg",
      "/images/dodge-challenger/4.jpeg",
      "/images/dodge-challenger/5.jpeg",
      "/images/dodge-challenger/6.jpeg",
      "/images/dodge-challenger/7.jpeg",
    ],
    description:
      "Feel the retro spirit reimagined with the 2023 Dodge Challenger — bold design meets turbocharged V4 performance.",
  },
  {
    id: "patrol-2023",
    name: "Patrol 2023",
    price: "AED400/day",
    deposit: true,
    transmission: "Automatic",
    seats: 4,
    luggage: 3,
    category: "SUV",
    images: [
      "/images/nismo/1.jpg",
      "/images/nismo/2.jpg",
      "/images/nismo/3.jpg",
      "/images/nismo/4.jpg",
      "/images/nismo/5.jpg",
    ],
    description:
      "Rule the road with the 2023 Patrol — a perfect SUV for exploring city streets or desert dunes in style and comfort.",
  },
  {
    id: "corvette",
    name: "Chevrolet Corvette 2024",
    price: "AED1200/day",
    deposit: true,
    transmission: "Automatic",
    seats: 2,
    luggage: 3,
    category: "Muscle",
    images: [
      "/images/corvette/1.jpeg",
      "/images/corvette/2.jpeg",
      "/images/corvette/3.jpeg",
      "/images/corvette/4.jpeg",
      "/images/corvette/5.jpeg",
      "/images/corvette/6.jpeg",
      "/images/corvette/7.jpeg",
      "/images/corvette/8.jpeg",
      "/images/corvette/9.jpeg",
      "/images/corvette/10.jpeg",
    ],
    description:
      "Rule the road with the 2023 Patrol — a perfect SUV for exploring city streets or desert dunes in style and comfort.",
  },
  {
  id: "patrol-2023-hawk",
  name: "Nissan patrol 2023 Platinum Black Hawk kit",
  price: "AED450/day",
  deposit: true,
  transmission: "Automatic",
  seats: 2,
  luggage: 3,
  category: "suv",
  images: [
    "/images/nissan-patrol/1.jpg",
    "/images/nissan-patrol/2.jpg",
    "/images/nissan-patrol/3.jpg",
    "/images/nissan-patrol/4.jpg",
  ],
  description:
    "Rule the road with the 2023 Patrol — a perfect SUV for exploring city streets or desert dunes in style and comfort.",
},
   
  {
    id: "mustang-2024",
    name: "Ford Mustang 2024",
    price: "AED400/day",
    deposit: true,
    transmission: "Automatic",
    seats: 4,
    luggage: 3,
    category: "Muscle",
    images: [
      "/images/mustang2024/1.jpeg",
      "/images/mustang2024/2.jpeg",
      "/images/mustang2024/3.jpeg",
      "/images/mustang2024/4.jpeg",
    ],
    description:
      "The 2024 Mustang Ecoboost blends American muscle heritage with modern technology for an exhilarating drive across the UAE.",
  },
  {
    id: "nissan-altima",
    name: "Nissan Altima 2023",
    price: "AED250/day",
    deposit: true,
    transmission: "Automatic",
    seats: 4,
    luggage: 3,
    category: "Economy",
    images: [
      "/images/nissan-altima/1.jpeg",
      "/images/nissan-altima/2.jpeg",
      "/images/nissan-altima/3.jpeg",
      "/images/nissan-altima/4.jpeg",
      "/images/nissan-altima/5.jpeg",
      "/images/nissan-altima/6.jpeg",
      "/images/nissan-altima/7.jpeg",
      "/images/nissan-altima/8.jpeg",
    ],
    description:
      "The 2024 Mustang Ecoboost blends American muscle heritage with modern technology for an exhilarating drive across the UAE.",
  },
];

export default cars;
